### ISSUE TITLE
[Feature request] Pglite & React only

### ISSUE THREAD

**Issue by volkandkaya** [teableio/teable#1004]
**Describe the solution you'd like**
I want to use the UI to connect to pglite without the backend.

**Describe alternatives you've considered**
Creating it myself or using an open source package.

**Additional context**
I believe you could create a annual developer license for those just wanting the UI. I already have a table built on Mantine/tanstack tables. However customers want to be able edit multiple rows etc.

**Comment by kpodp0ra** [comment]
Unfortunately, this is out of scope for the project. Connecting a WebSocket directly to a database without a backend is likely very difficult or even impossible, and there doesn’t seem to be much interest in this feature.

You can track this issue for bring-your-own-database approach: #556
