### ISSUE TITLE
In table view, be able to scroll horizontally using Shift+Scroll

### ISSUE THREAD

**Issue by dctremblay** [teableio/teable#1074]
**Is your feature request related to a problem? Please describe.**
On most web page where you can scroll horizontally, you can with Shift+Scroll, however it doesn't seem to work on Teable.

**Describe the solution you'd like**
Shift+Scroll in a table view make it scroll horizontally.

**Describe alternatives you've considered**
I'm scrolling using the bottom scrollbar, which works well.

**Comment by nicholas-mn** [comment]
To add to this - shift+tab to navigate to the cell to the left. Only tab (navigate to the right) is supported at the moment.

**Comment by kpodp0ra** [comment]
@dctremblay what OS are you using?

**Comment by dctremblay** [comment]
Kubuntu 22.04 and Chrome 131.0.6778.85
