### ISSUE TITLE
Add permissions: You can only edit but not delete data

### ISSUE THREAD

**Issue by wenchanggai** [teableio/teable#1080]
I hope you have a permission that can be edited, but you cannot delete data. Now with the editing function, the salesperson can delete all data, which is a bit unreasonable.And I can't edit the view, right? I set it up that I can only view my own view. If he changes it, won't he be able to see all the data again?

![image](https://github.com/user-attachments/assets/8f905c4f-e1f5-41b0-86db-efbc219381bd)

**Comment by tea-artist** [comment]
We provide a more comprehensive permission matrix in the Enterprise version
https://help.teable.cn/ji-ben-gong-neng/quan-xian-guan-li
