### ISSUE TITLE
I can't delete views in enterprise version

### ISSUE THREAD

**Issue by romainds-tech** [teableio/teable#1123]
**Describe the bug**
I can't delete views, I added some views and now I want delete them and I can't, when I left click on top on the view name nothing happen

**To Reproduce**

1. Go to new view created on enterprise version
2. Click left on the name on top
3. Nothing happen we can't delete the view

**Expected behavior**
Possibility to delete the new view

**Screenshots**
![CleanShot 2024-12-01 at 15 46 03](https://github.com/user-attachments/assets/ef2fd4c6-8aa9-4b54-957f-92e711f06f8e)

** Client (please complete the following information):**
- OS: macos
- Browser chrome
- Version 131.0.6778.86 

**Platform (Please tell us which deployment version you are using)**
image: ghcr.io/teableio/teable-ee

Other info
I don't have any authority role

**Comment by tea-artist** [comment]
I tried it, and it doesn't seem to work when I click the icon, but it works when I click the text.

**Comment by romainds-tech** [comment]
After multiple try I got it, but I don't think this a normal behavior.

To be able to delete it seems we need to
- LEFT click after hoover the button WHEN WE ARE IN THE VIEW

Normal behavior -> RIGHT click to delete a view no matter which view you're in

Can you confirm ? 

btw I'm on macbook (with pad) idk if that change something ?

**Comment by tea-artist** [comment]
I agree we should unify interaction expectations, which will improve here
