### ISSUE TITLE
Migration error because of collaborator table

### ISSUE THREAD

**Issue by julien731** [teableio/teable#1124]
## Context

I am running an old-ish version of Teable. Version 1.2.0 beta. When trying to upgrade to the latest version, I am running into a migration issue.

## Steps to Reproduce

1. Install Teable 1.2.0 beta
2. Pull the latest images with `docker compose pull`
3. Run the containers with `docker compose up`

## Expected

The migration should run.

## Actual

```
ERROR:  insert or update on table "collaborator" violates foreign key constraint "collaborator_user_id_fkey"
```

<img width="996" alt="image" src="https://github.com/user-attachments/assets/dc45530a-965e-4410-8847-87ee4d99ecd2">

**Comment by boris-w** [comment]
It seems that the user_id field in the collaborator table does not have corresponding records found in the users table.
You may need to query the collaborator table for these orphaned records and clean them up using SQL.

**Comment by julien731** [comment]
Thanks a lot for your help @boris-w all good now after cleaning up the collaborator table.
