### ISSUE TITLE
connection limit on docker install of ce

### ISSUE THREAD

**Issue by ahmadkakarr** [teableio/teable#1150]
This limit helps us maintain system stability and efficiency, ensuring a good experience for all users.
dear community but why in docker install why its there and no simple way to update it ???
for me
The maximum number of database connections is 20 and the current connections is 0

**Comment by tea-artist** [comment]
here is the env:
DEFAULT_MAX_BASE_DB_CONNECTIONS
```bash
DEFAULT_MAX_BASE_DB_CONNECTIONS=20
```

**Comment by ahmadkakarr** [comment]
https://help.teable.io/deployment/environment-variables
Not listed here

**Comment by kpodp0ra** [comment]
Created issue on docs repo. Closing this as resolved.
