### ISSUE TITLE
403 after Login

### ISSUE THREAD

**Issue by 343max** [teableio/teable#1176]
**Describe the bug**

Starting today I can't login anymore. Instead I get a big fat 403 error.

**To Reproduce**

Login.

**Expected behavior**

See my spaces.

**Screenshots**

<img width="637" alt="image" src="https://github.com/user-attachments/assets/09dd1701-04e2-4bd3-bee6-eca82fcf6fba" />

** Client (please complete the following information):**

- OS: macOS/iOS latest
- Safari

**Platform (Please tell us which deployment version you are using)**

docker-standalone.

**Comment by tea-artist** [comment]
Fixed in the latest version
