### ISSUE TITLE
Long Text Fields Don't Wrap Wrap Correctly

### ISSUE THREAD

**Issue by dataskis** [teableio/teable#1178]
When using Long Text field , words don't wrap correctly, but instead continue on the next line, instead of being carried over to the next line.

This is reproducible for any text height. 

**To Reproduce**

1. Create a new column with type "Long Text"
2. Write some text in a Long Text cell, and make sure that words towards the end of the line are long enough to where they would normally wrap.
3. Apply changes to the cell. The cell stops word wrapping, causing readability issues, and also consistency issues between cell view & edit modes.

**Expected behavior**
Word wrapping in both edit text and standard display mode.

**Screenshots**

Works normally in edit mode:
![Edit Mode](https://github.com/user-attachments/assets/34546a40-0aa8-40f0-8f71-c7a2fc7b8794)

Once changes are applied and the cell goes into standard display mode:
![View Mode](https://github.com/user-attachments/assets/e682906f-1811-45e3-bdac-11772a5a7ac5)

** Client (please complete the following information):**

- Browser: Tried Chrome, Edge

Cloud version teable.io (also tried Docker version)

**Comment by tea-artist** [comment]
same as #1177
