### ISSUE TITLE
Thumbnail is a Text File with Image Path Instead of Image

### ISSUE THREAD

**Issue by alifyasa** [teableio/teable#1206]
**Describe the bug**

When uploading an image, the thumbnail generated is a text file containing the path to the intended image instead of the actual image file.

**To Reproduce**

1. Upload an image
2. Refresh to see the thumbnail version

**Expected behavior**

Thumbnail is an image

**Screenshots**

Example of the file and the thumnail generated

![Screenshot 2024-12-30 154223](https://github.com/user-attachments/assets/9a9a6420-8f1d-4fb9-bd6e-fbca64250d7c)

The `_lg` and `_sm` is a text file. The bucket name is `teable-private`.

![image](https://github.com/user-attachments/assets/d5cd2191-5b5d-4575-95b7-477706c37289)

Example of the generated thumbnail in gallery view. 

![image](https://github.com/user-attachments/assets/a363f2ec-8ba9-4f5e-ae1a-a1da1c97a692)

**Client**

- OS: Microsoft Windows 11 Home Single Language
- Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101 Firefox/133.0

**Platform**

Docker image `ghcr.io/teableio/teable:1.5.2-build.684-amd64`.

**Additional context**

 1.  I can download the original image, just can't see their thumbnails

**Comment by tea-artist** [comment]
It seems that PUBLIC_ORIGIN is not configured correctly. PUBLIC_ORIGIN should be configured as the address you are currently accessing (like http://192.168.xx.xx).

**Comment by alifyasa** [comment]
> It seems that PUBLIC_ORIGIN is not configured correctly. PUBLIC_ORIGIN should be configured as the address you are currently accessing (like http://192.168.xx.xx).

I am accessing it from https://data.alifyasa.com and PUBLIC_ORIGIN is https://data.alifyasa.com.

![image](https://github.com/user-attachments/assets/ae755d5f-e073-4517-a484-b8803a445411)

**Comment by tea-artist** [comment]
![image](https://github.com/user-attachments/assets/a4570d4b-f19b-4e7a-9365-e22da22d3874)

Could you provide browser console error message in this situation to locate the problem.

**Comment by alifyasa** [comment]
![image](https://github.com/user-attachments/assets/5a73af12-4c30-4dc5-b7e8-14efa974ca8f)
![image](https://github.com/user-attachments/assets/92cb250c-f9e1-4d34-abb2-5c2cf9580809)

**Comment by tea-artist** [comment]
The request is blocked due to your server's Content-Security-Policy (CSP) and CORS settings. Please update your Nginx configuration to allow cross-origin requests and adjust the 'block-all-mixed-content' directive for `teable-private.getawey.storjsshare.io`.

**Comment by alifyasa** [comment]
I switched my S3 provider to Amazon (previously an S3 compatible service) and it works now. Although now it fetches the full image everytime and does not generate a thumbnail. Thank you for your help.
