### ISSUE TITLE
Support TSV uploading

### ISSUE THREAD

**Issue by boxxxie** [teableio/teable#427]
currently only CSV uploading is supported

it's very likely that the CSV parsing library that is being used also supports TSV.

**Comment by caoxing9** [comment]
I've rarely heard of this format, i'll know it and make it possible.
appreciate for suggestion~

**Comment by boxxxie** [comment]
this is quite a popular format, and most spreadsheet programs allow it as input and output. it is a subset of CSV, which is why a CSV library should support it.
