### ISSUE TITLE
Issue: Image previews are broken in self-deployment.

### ISSUE THREAD

**Issue by hmmhmmhm** [teableio/teable#429]
I'd like to suggest an enhancement for Teable's list page. It would be highly beneficial if the list view could include previews of images that are contained within each row.

This feature would significantly improve the user experience by allowing users to quickly visualize the content without having to navigate away from the list page. Implementing image previews could make data interpretation more intuitive and efficient, especially for databases that are heavily reliant on visual content.

**Comment by tea-artist** [comment]
We've identified an issue where images can't be loaded in the Self Deploy version of Teable (teable.io is fine) due to domain policy reasons. We plan to fix this shortly.

**Comment by Pengap** [comment]
Support for using environment variables to specify the address of optimized remote images has been introduced. Simply set the variable when utilizing Teable's official Docker image by configuring `NEXT_ENV_IMAGES_ALL_REMOTE=true`. To activate restrictions on remote image optimization, you must manually adjust [next.config.js](https://github.com/teableio/teable/blob/develop/apps/nextjs-app/next.config.js#L164) and rebuild your custom image.
