### ISSUE TITLE
[Feature request] OIDC login

### ISSUE THREAD

**Issue by MitPitt** [teableio/teable#434]
Currently only email+password login is available. OIDC will allow teable to have alternatives like Google login, self-hosted OIDC servers, and many others. It is crucial for me to have this alternative for my use case.

**Comment by boris-w** [comment]
> Currently only email+password login is available. OIDC will allow teable to have alternatives like Google login, self-hosted OIDC servers, and many others. It is crucial for me to have this alternative for my use case.

Hey, I feel like I might understand what you're saying. Is this what you want?  https://github.com/teableio/teable/pull/432

**Comment by boris-w** [comment]
> hi @boris-w that's greet , but OIDC alone is not enough I think , since the application can be used in local hosting or in internal application etc .. , a more control is needed on user registration , creation , such as giving the admin or group of admin the option to create user roles and permissions , and the option to create / upload or import a list of users and roles / permissions , for a example a super admin can have all options , custom admin can have the option to add new users but ca not modify or delete a role or user and vise versa etc .. it's partly implemented in the Api , but it need to be more related to users and Authentications etc ..

Absolutely, I completely agree with you. Enhancing user registration and management capabilities, including user roles, permissions, and authentication controls, is definitely on our radar. We're actively working on plans to address these aspects and incorporate them into our platform. Your input is greatly appreciated, and we're committed to improving the user experience in this regard. Thank you for sharing your thoughts!

**Comment by Node815** [comment]
I came here to ask for this as well.  I also use Authentik, but with a generalized OIDC integration, this would completely enhance the user experience.  I run this locally for now, but want to also disable user registration as an option.   My goal is for myself and my wife to use it to record certain aspects of our health, such as pain logs, sleep logs and more.   I also use it for different data sets I have.  For her to use this, it would be easier to just sign in automagically (OIDC) on our domain  rather than fuss with a UN/PW combo. :)

**Comment by Zhuangkh** [comment]
It looks like https://github.com/teableio/teable/pull/617 has made a general implementation of OIDC. Will it merge into the next release?

**Comment by boris-w** [comment]
> It looks like #617 has made a general implementation of OIDC. Will it merge into the next release?

This PR has fallen by the wayside,  I’ve been planning on resurrecting it lately.

**Comment by tlzzu** [comment]
@boris-w Can it support OAuth 2.0?

**Comment by boris-w** [comment]
> [@boris-w](https://github.com/boris-w) Can it support OAuth 2.0?它支持 OAuth 2.0 吗？

We don't support pure OAuth 2.0 because it's an authorization framework without standardized user info endpoints or response formats. Each provider (Google, GitHub, Microsoft, etc.) returns user data differently, requiring custom integration code for each.
