### ISSUE TITLE
there is no ui for listing all registered user in the app , and what is size of each user space 

### ISSUE THREAD

**Issue by mz0in** [teableio/teable#442]
there should be a ui element that show all resgistered user and their role , space usage , rest password , while this can be partly achieved by accessing the Postgres database but the availability in the Owner/Admin  ui is more convinient

**Comment by tea-artist** [comment]
We are planning Admin-related features and will create a discussion for everyone to preview when we have a draft.

We'll consider it along with the registration ban #441

**Comment by mz0in** [comment]
Thanks, love to hear that
