### ISSUE TITLE
Paste does not paste

### ISSUE THREAD

**Issue by loranger** [teableio/teable#467]
Hello,

I use the latest teable docker image, but I cannot paste any cells.

Here is a little screen cast of my issue:

https://github.com/teableio/teable/assets/6014/f8054a55-dcee-438e-a85a-852d1132ea87

By the way, thank you so much for this awesome alternative to Airtable/Baserow/Seatables, etc…!
This beta version is far better than the competitors 💪🏻

**Comment by tea-artist** [comment]
Due to browser security restrictions, asynchronous clipboard access can only function under HTTPS. Therefore, you need to configure an HTTPS certificate.
