### ISSUE TITLE
docker standalone config is not working with current .env

### ISSUE THREAD

**Issue by Minifiles** [teableio/teable#471]
db_migrate will run successfully, but the Teable app is unable to connect to PostgreSQL with the current .env configuration.

Changing 
`PRISMA_DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}`
to 
`PRISMA_DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@teable_db:5432/${POSTGRES_DB}`
fixed the problem for me.

**Comment by Pengap** [comment]
I probably copied it when I wrote it and forgot to change it, I'll modify the file later :relieved:
