### ISSUE TITLE
Increase Row limits on a table

### ISSUE THREAD

**Issue by brickdatalab** [teableio/teable#485]
How can the maximum rows be extended since it's limited to ~100k rows? There are no options in the interface that lets you upgrade

**Comment by tea-artist** [comment]
The saas version is currently available in a free preview, to prevent abuse, we have set a line limit of 100k for each table.
Please click on your space, copy the URL and send it to support@teable.io and we'll expand your space by 1m rows. If you have more needs, you can tell us the use scenario directly in the email, and we will be happy to discuss the solution with you.
> Click here in the home page, and copy the URL
<img width="345" alt="image" src="https://github.com/teableio/teable/assets/113977203/2738fac4-4191-43ac-910b-a8d886d9e873">
