### ISSUE TITLE
captcha in form

### ISSUE THREAD

**Issue by tylerdurden4285** [teableio/teable#486]
Forms have a lot of elements, however to help combat spam it would be good to have an option for captcha. Forms can then safely be used publicly unlike currently.

**Comment by tea-artist** [comment]
Is that what you what 😀

<img width="440" alt="image" src="https://github.com/teableio/teable/assets/113977203/0d30ae36-1be8-44ff-a640-d636de0baf8c">

**Comment by tylerdurden4285** [comment]
Thanks for reply. I was thinking more along the lines of captcha like
recaptcha for example.

**Comment by tea-artist** [comment]
I see, you want to prevent spam submissions like bots. But I'm not sure if this is a just-needed scenario, and unless the form submission information is very sensitive, the risk should be limited.
Maybe a possible alternative is to require users to log in before submitting.

**Comment by tylerdurden4285** [comment]
Thanks for your reply. Yes bots, i was unclear on that - my bad. The
password will help somewhat for basic bots but ones that just enter the
static password will easily bypass this because they are randomized.
Captcha is a standard option these days for most public facing forms and
resolve a massive problem of bots spamming the database rows.

**Comment by mz0in** [comment]
I also don't see a need for captcha in form it will slow the data entry flow , since there is a password and the spammers   shouldn't be aware of it the password is more than enough

**Comment by tylerdurden4285** [comment]
It's common practice for forms and optional like the other fields at the
creators discretion, its not mandatory.

**Comment by tylerdurden4285** [comment]
> I also don't see a need for captcha in form it will slow the data entry flow , since there is a password and the spammers   shouldn't be aware of it the password is more than enough 

If you have a public form with a password to complete the form then you need to publicly announce said password. This is a risk as bots can easily spam the heck out of your database. A simple captcha option in the existing field options is a solution to this. 

Edit: The captcha is optional like any other form field element. Like most other form providers have.

**Comment by tylerdurden4285** [comment]
Hey, just checking in on this to see if it is in the roadmap at all?

**Comment by tea-artist** [comment]
Due to the lack of significant necessity, we have not included it in our roadmap.
