### ISSUE TITLE
[Feature request] Connect to Existing User Databases

### ISSUE THREAD

**Issue by sqkkyzx** [teableio/teable#489]
## Description

I currently possess several databases and tables, for which I have written scripts for automating data table updates, as well as numerous custom trigger functions. I wish for `Teable` to be able to connect to these databases and tables to display them as tables and other views without the mandatory use of the `Teable API` for updates.

## Additional Information

An acceptable alternative would be for `Teable` to provide a database connection scheme that allows full functionality for SELECT/UPDATE/DELETE operations.

I am currently using Nocodb, and you can review how they implement and provide the capability to connect to external databases for the open-source version.

Frankly speaking, although `Teable` attracts me with some of its features, I will not switch to `Teable` if it cannot allow me to connect to external databases. As a community user, I may not bring direct profit, but I kindly ask if there is any plan for such feature development, please inform me. This is because I am very interested in migrating to `Teable` for the following features:

- `Teable` allows custom naming of field names in hosted tables, and the displayed names can differ from the database field names. On the contrary, Nocodb messes everything up by changing all database field names to filed, filed1, filed2...
- `Teable` can change text fields to single-choice and automatically add all existing text values as options. Meanwhile, changing text fields to single-choice in Nocodb results in all values being displayed as blank. The only solution is to manually add all values as options, which becomes daunting when multiple fields need modification and each has more than ten types of values.
- `Teable` seems to have better performance.

---

**Comment by mz0in** [comment]
There are so many things teable is ahead , I think such a future will be on the roadmap regarding how  important it's
