### ISSUE TITLE
Error while trying to create an access token

### ISSUE THREAD

**Issue by luanjpb** [teableio/teable#497]
Currently im testing the free saas preview of  Teable. I'm trying to generate an access token to connect it to my application. Unfortunattely every time i get a message that says "internal_server_error", with no adtional information. I even tried to recreate the requisition using curl, but still got the error. How can i proceed?

![Sem título](https://github.com/teableio/teable/assets/12876838/6eb03697-0222-4f0e-980c-6bc09d858b71)

**Comment by krugerm** [comment]
For me, this only works when creating PATs expiring in 7 days.

**Comment by krugerm** [comment]
This is a date formatting bug.

For me, when set to 90 days expiry, the form submits a payload which returns an internal error:
{"name":"test","description":"test","scopes":["field|read","record|read"],"expiredTime":"**24/06/2024**"}

Modifying the payload with the date in mm/dd/yyyy format results in success:
{"name":"test","description":"test","scopes":["field|read","record|read"],"expiredTime":"**06/24/2024**"}

Fix:
Edit **apps/nextjs-app/src/features/app/blocks/setting/access-token/form/ExpirationSelect.tsx** and find/replace all "toLocaleDateString()" with "toISOString()"

**Comment by boris-w** [comment]
Yes, we have also identified it as a bug caused by date formatting. I will fix it.
