### ISSUE TITLE
Single column data accumulation

### ISSUE THREAD

**Issue by simonzcx** [teableio/teable#500]
Whether to support single-column data accumulation
是否支持单列数据累加，类似excel里面的累积公式

**Comment by tea-artist** [comment]
You can click on the bottom of the column and there will be a formula for preforming aggregation.
<img width="666" alt="image" src="https://github.com/teableio/teable/assets/113977203/e7f40cca-c5fa-4b90-9950-19f6488810c0">

**Comment by simonzcx** [comment]
Ok tks, but what I hope to achieve is the following, do you support it now? or will support it in the future
| Date     | Cost | Total Cost  |
|----------|------|-------------|
| 2024/3/1 | 10   | 10          |
| 2024/3/2 | 15   | 25          |
| 2024/3/3 | 15   | 40          |

**Comment by tea-artist** [comment]
We might consider doing something similar with a view called `SQL view`, where you can use SQL directly to perform arbitrary calculations and groupings.

**Comment by simonzcx** [comment]
Ok. expect it so much

**Comment by simonzcx** [comment]
Ok. expect it so much
