### ISSUE TITLE
Filtered View New Row Creation hidden

### ISSUE THREAD

**Issue by jackoregankenny** [teableio/teable#502]
This functionality works for group views, If I make a new entry under a group, it will carry the group with it. However when I create a new entry under a filtered view it will immediately vanish as the filter is not applied to it. 

I think this is a small oversight in expected behaviour, testing others like Nocodb and Airtable they do this. Just a small flag

**Comment by kpodp0ra** [comment]
I understand the frustration with new entries disappearing when created under a filtered view. However, applying the current filter's criteria to default values for new records is a bit tricky. Filters can be more complex than groups, and creating an algorithm that reliably guesses default values based on the filter conditions would be very challenging.

For example, filters could involve things like numerical ranges, text matching, or multiple conditions, which would make it difficult to predict what a new record should inherit. Unlike groups, where the field simply carries the group label, filters involve more dynamic logic, and we'd need to account for a lot of edge cases.

Given this complexity, I'm marking this as won'tfix for now. If you have a specific approach in mind for how this could work, feel free to clarify, and we can revisit the issue.

**Comment by kpodp0ra** [comment]
Related #719
