### ISSUE TITLE
Bug found in copying share link

### ISSUE THREAD

**Issue by jaherron** [teableio/teable#506]
When trying to copy the sharing link after enabling sharing for a view, the copy button causes this error in the browser console.
I don't know if this is a real bug in the software or just an artifact of me running a self-hosted instance.

```plaintext
[viewId]-b6bf1d65ae94c4f0.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'writeText')
    at y ([viewId]-b6bf1d65ae94c4f0.js:1:18731)
    at test.n.<computed> (_app-0cdcc7521fdc94d5.js:95:15319)
    at Object.eB (framework-922e6b3f191606ca.js:25:14910)
    at eH (framework-922e6b3f191606ca.js:25:15064)
    at framework-922e6b3f191606ca.js:25:33370
    at re (framework-922e6b3f191606ca.js:25:33469)
    at rt (framework-922e6b3f191606ca.js:25:33883)
    at framework-922e6b3f191606ca.js:25:39339
    at uP (framework-922e6b3f191606ca.js:25:96306)
    at eM (framework-922e6b3f191606ca.js:25:14048)
```

**Comment by tea-artist** [comment]
It looks like the browser doesn't support the `clipboard` API.
What is your browser and whether you have enabled https?

**Comment by jaherron** [comment]
I am self-hosting Teable, so it isn't behind HTTPS.
I am using Google Chrome.

**Comment by tea-artist** [comment]
We are using [this API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard) for the copy/paste feature, so it only works behind HTTPS.

**Comment by jaherron** [comment]
Is there any way to add the SSL cert for the domain I'm using to my self-hosted instance?

**Comment by jaherron** [comment]
I'm marking this as

**Comment by jaherron** [comment]
I'm closing this as not planned since I applied HTTPS to Teable using Nginx Proxy Manager.
