### ISSUE TITLE
attachment is not shown 

### ISSUE THREAD

**Issue by mz0in** [teableio/teable#512]
there is no indicator in the attachment column that their is an attachment there , normally a file name , or a small preview should be displayed , also an option to upload file attachment to AWS S3 or compatible service.

**Comment by tea-artist** [comment]
Are you on the self-host version? this may be the reason #429

**Comment by mz0in** [comment]
> Are you on the self-host version? this may be the reason #429

yes Thanks  ,this fixed the issue : NEXT_ENV_IMAGES_ALL_REMOTE=true
 any plan for  the other part an option  to save the attached file locally or on  Amazon S3 or compatible providers such as CloudFlare R2 , minio etc

**Comment by sanwacompany** [comment]
@mz0in Hi there, could u pls kindly share your docker-compose.yml and .env file pls? I just add NEXT_ENV_IMAGES_ALL_REMOTE=true but still have no previews of attachements.  I've spent 2 days on working this out and going crazy....
