### ISSUE TITLE
[Feature request] Group by "Range"

### ISSUE THREAD

**Issue by vasnt** [teableio/teable#518]
Group by  user-defined custom RANGE i.e. "1 to 10" , "10 to 20" etc. instead of each number.

![image](https://github.com/teableio/teable/assets/117589240/da88ab8f-55a6-4d2e-b1d4-668fa0b8bbd5)

**Comment by tea-artist** [comment]
You can group by a formula as a workaround.
`FLOOR({Seats}, -1) & " to " & FLOOR({Seats} + 10, -1)`

<img width="673" alt="image" src="https://github.com/teableio/teable/assets/113977203/a4f06518-6a61-4b95-bde4-70cf917cc6b3">
