### ISSUE TITLE
[Feature Request]: Group by date, not datetime

### ISSUE THREAD

**Issue by BieliaeVlas** [teableio/teable#526]
I have a simple application where I store my trainings I do at gym. Basically, I want to group my _training_ table by date so I can monitor list of exercises I was doing at a certain day.

Right now, I see it groups by datetime, so it's not relevant for me. I tried to drop Time Formatting, but it didn't help.

![2024-04-02 18 45 29](https://github.com/teableio/teable/assets/42597604/fd87ee01-d132-40bc-8c4a-4799cb0d6a0e)
![2024-04-02 18 45 45](https://github.com/teableio/teable/assets/42597604/ab468b71-9a0d-46a3-a3da-a9216f144f2d)

**Comment by tea-artist** [comment]
I agree with you that value should be grouped in display format and we will fix it.
Currently, you can use additional formulas as a workaround.

`DATETIME_FORMAT({CreatedTime}, 'YYYY-MM-DD')`
<img width="711" alt="image" src="https://github.com/teableio/teable/assets/113977203/4789b19e-7077-4105-8223-f74aa330f950">

**Comment by BieliaeVlas** [comment]
Great, it works for me! Thank you so much
