### ISSUE TITLE
`PUBLIC_DATABASE_PROXY` isn't documented anywhere, but needed for Postgres Access

### ISSUE THREAD

**Issue by 343max** [teableio/teable#532]
When trying to setup postgres access (yeah!) on my self hosted database I receive and error:

> not_found
> PUBLIC_DATABASE_PROXY is not found in env

But I can't find anything what this variable should contain.

**Comment by tea-artist** [comment]
You need to configure the env according to the steps below:
https://help.teable.io/deployment/docker-compose#starting
We have fixed some errors in the previous document, The configuration for PUBLIC_DATABASE_PROXY can be found explained here:
https://help.teable.io/deployment/environment-variables
> Required to enable the database connection feature in Base.
> The public IP address or domain of the server hosting the database + the database service port exposed by Docker (default is 42345) Example: example.com:42345

**Comment by mmospanenko** [comment]
Will be good to not expose postgres port outside, I use traefik and one postgres for multiple services so will be great to have lightweight container (or just endpoint as proxy in main container). Anyway this project is awesome, having proxy for postgres is more than I even thought could be here, really everything what I needed (or coming soon like gantt or comments and dashboards). Thank you!
