### ISSUE TITLE
请问是 改那个 .env文件呢?求助 请问怎么连接 不是在docker里面的，本地的pg数据库

### ISSUE THREAD

**Issue by lucktoo** [teableio/teable#538]
请问是 改那个 .env文件呢?求助
请问怎么连接 不是在docker里面的，本地的pg数据库

文件下有2个.env文件
1./Users/bluesky/Documents/teable-develop/dockers/examples/standalone/.env
2./Users/bluesky/Documents/teable-develop/dockers/.env
3./Users/bluesky/Documents/teable-develop/dockers/examples/standalone/docker-compose.yaml 这个文件?
如下我注释掉了 teable-db

```
teable-db:
  #   image: postgres:15.4
  #   restart: always
  #   ports:
  #     - '42345:5432'
  #   volumes:
  #     - teable-db:/var/lib/postgresql/data:rw
  #     # you may use a bind-mounted host directory instead,
  #     # so that it is harder to accidentally remove the volume and lose all your data!
  #     # - ./docker/db/data:/var/lib/postgresql/data:rw
  #   environment:
  #     - TZ=${TIMEZONE}
  #     - POSTGRES_DB=${POSTGRES_DB}
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #   networks:
  #     - teable-standalone
  #   healthcheck:
  #     test: ['CMD-SHELL', "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
  #     interval: 10s
  #     timeout: 3s
  #     retries: 3
```
终端报错:
docker-compose up -d
service "teable-db-migrate" depends on undefined service teable-db: invalid compose project

**Comment by tea-artist** [comment]
Please do not open new issues repeatedly. Reply below the original issue #533   and we will be notified
