### ISSUE TITLE
There is no Ctrl Z options 

### ISSUE THREAD

**Issue by mz0in** [teableio/teable#541]
some times when working with data and mistyping a filed or a couple of cells that was highlighted would cause the data to be deleted / altered in unmanned way , that will cause data lose , and since the data is live saved , a Ctrl Z option is needed

**Comment by tea-artist** [comment]
This is on the roadmap🥹

**Comment by almereyda** [comment]
Versioning of historical records is now available, which makes it possible to implement undo/redo functionality. It will be interesting to consider it together with real-time collaboration.

**Comment by tea-artist** [comment]
@almereyda Yes, undo-redo is on the way. 🫡
