### ISSUE TITLE
Filtering Lookup does not work if the source field is "User"

### ISSUE THREAD

**Issue by solankimihir** [teableio/teable#543]
**Describe the bug**
If you lookup any field which is a "User" type from Table B to Table A, and then apply filter on that lookup. The filter will not work correctly.

**To Reproduce**
1. Create Table A with a column for "User Type"
2. Create Table B
3. Link Table A and B [(Table A)One to Many(Table B)]
4. In Table B , create a new column with "Look up" to Table A "User Type" column
5. Apply Filter in Table B. The filter will not work correctly.

**Expected behavior**
I should be able to filter based on user name in Table B

**Screenshots**
Table A:
![image](https://github.com/teableio/teable/assets/66866380/6375d383-cb52-43e0-ac82-857b6b466af8)

Table B:
![image](https://github.com/teableio/teable/assets/66866380/acc0434a-16e4-46a5-9a37-48b5588cb00b)

Relation of Table A and Table B:
![image](https://github.com/teableio/teable/assets/66866380/1227e1be-b906-4708-8a6c-176988a777c9)

Filter Applied:
![image](https://github.com/teableio/teable/assets/66866380/b8e4805d-15b1-44d3-b4ce-6a01036449f5)

After applying filter, the results is blank.
Ideally, I should be seeing 2 records mapped to me.
![image](https://github.com/teableio/teable/assets/66866380/16163056-eeb9-4c75-8c75-a9bbd0495291)

** Client (please complete the following information):**
 - OS: [e.g. iOS] : Windows 11
 - Browser [e.g. chrome, safari] : Firefox
 - Version [e.g. 22] 124.0.2 (64-bit)

**Platform (Please tell us which deployment version you are using)**
- Teable IO
- StandAlone Docker

**Comment by tea-artist** [comment]
Thank you for your detailed feedback, We reproduced the bug and will fix it soon.
