### ISSUE TITLE
[FR] Is there any plan to support any installation package?

### ISSUE THREAD

**Issue by hustrjh** [teableio/teable#566]
I appreciate the idea of the project a lot. But it would be more easy to install it with installation package for regular users.
Is there any plan to support any installation package like [NocoDB](https://github.com/nocodb/nocodb/releases)?
Thanks for creating such good project. ❤

**Comment by tea-artist** [comment]
Thanks for your ❤.
Teable does not currently support direct manipulation of existing tables, so we cannot support the way like NocoDB. 
the related question is here #556

**Comment by hustrjh** [comment]
Maybe I didn't make it clear. I just wonder if Teable would support **Windows installer** or **Standalone Windows Binaries**. Thanks for your reply.😄
