### ISSUE TITLE
In version 1.20, I am having trouble connecting to my local pg (PostgreSQL) database,

### ISSUE THREAD

**Issue by lucktoo** [teableio/teable#569]
In version 1.20, I am having trouble connecting to my local pg (PostgreSQL) database, whereas with version 1.10, following your instructions, I was successful. Are the steps the same for this version, or do I need different procedures?

Please assist me in connecting to the local PostgreSQL database in version 1.20, as I encountered various issues with this version despite successfully doing so with version 1.10 using the previously provided steps. 

Translation:
"In version 1.20, I need help connecting to my local PostgreSQL database. In version 1.10, I managed to connect successfully using the steps you provided earlier. However, I'm facing several problems with this newer version. Could you confirm if the connection steps are identical, or do I require different procedures for version 1.20?"

**Comment by kpodp0ra** [comment]
Hi! I’m temporarily closing this issue for now. Please provide any screenshots or error messages you're encountering so I can assist you further. Once I have more details, I’ll be happy to help you resolve the connection issue with version 1.20.

Looking forward to your response!
