### ISSUE TITLE
Some API endpoints returning 403 error code even with all scopes enabled

### ISSUE THREAD

**Issue by jaherron** [teableio/teable#572]
**Describe the bug**
Even when a token has all scopes enabled, some API endpoints result in a 403 Forbidden error.

**To Reproduce**

1. Create an API token and enable all scopes.
2. Using the HTTP requesting tool of your choice, attempt to send a GET request to [Teable URL]/api/space or [Teable URL]/api/base/access/all.

**Expected behavior**
I expected to see a list of spaces or a list of bases when requesting to those endpoints.

**Screenshots**
![image](https://github.com/teableio/teable/assets/40708782/860f4cdf-ddbf-49c6-89ff-c4c8ff4249f9)
![image](https://github.com/teableio/teable/assets/40708782/cf60ce37-4de7-4912-822b-a1a798dae5e7)
![image](https://github.com/teableio/teable/assets/40708782/942741a1-3c08-447e-927b-7db181d0807e)

**Client (please complete the following information):**

- OS: MacOS Sonoma
- Browser: Chrome
- Version: 123.0.6312.124
- HTTP Request tool: [Postman](https://postman.co)

**Platform (Please tell us which deployment version you are using)**
docker-standalone

**Comment by tea-artist** [comment]
The endpoint `Get all bases` is for all bases in all spaces, so you need to open up access to all spaces and `Get all spaces` is the same

Now you're only allowing one specific space

<img width="930" alt="image" src="https://github.com/teableio/teable/assets/113977203/109056df-511e-4259-b640-e28d5f96c76b">

**Comment by boris-w** [comment]
Hello, currently, our token requires specifying the access (space or base). Therefore, these two endpoints do not support token-based access. Since you've chosen a space as your access, you should be aware of your spaceId. Please use this spaceId to access all bases under this space via api/space/:spaceId/base (GET), instead of attempting to access all available bases.

**Comment by jaherron** [comment]
I'm closing this issue since it's old and I've been writing some scripts that use the API successfully.
