### ISSUE TITLE
[FR] Is there any plan to support K8 deployment?

### ISSUE THREAD

**Issue by amitoo7** [teableio/teable#579]
Thanks for creating such a great project. Is there any plan for building a Helm chart to deploy this project on the Kubernetes cluster if so I can help. Let me know

**Comment by dalemccrory** [comment]
I would be interested in this as well.

**Comment by tea-artist** [comment]
We may consider migrating the current deployment environment of teable.io to K8s. At that time, we will release the Helm chart config.

**Comment by pand-app** [comment]
FYI : https://gitlab.com/vigigloo/tools/teable/

**Comment by tea-artist** [comment]
I have prepared a helm chart to deploy all the services that teable depends on. I hope this will help
@dalemccrory @amitoo7
