### ISSUE TITLE
Unable to get filtered results when filter is applied on a field where users looked up from another table.

### ISSUE THREAD

**Issue by solankimihir** [teableio/teable#584]
**Describe the bug**
If you have a field which looks up users from another table, and then you try to apply filter to that field to filter out rows mapped to specific user, I get 0 records.

**To Reproduce**
Create a table with clients as such:
![image](https://github.com/teableio/teable/assets/66866380/45ff4958-35a3-420b-a2a8-851d3d08759b)

Create a table with Tasks (Linking to the clients table above):
![image](https://github.com/teableio/teable/assets/66866380/c85dfc27-5270-4b5d-907f-d45bff9ded7e)

Now Lookup the "Mapped to" user from Clients table in Tasks Table:
The Tasks table would look as follows:
![image](https://github.com/teableio/teable/assets/66866380/3a49e264-b1b2-495f-ad44-eb99f1b5ef8d)

Now apply filter for a specific user:
![image](https://github.com/teableio/teable/assets/66866380/6470dff4-005a-45ba-9b00-6e23400ae6fd)

After applying filter, the filters, 0 records are fetched:
![image](https://github.com/teableio/teable/assets/66866380/befea161-0d4e-48a6-839a-7c82ffcd361a)

**Expected behavior**
Tasks mapped to that specific user must be shown as filtered rows

**Screenshots**
Screenshots in line with description above.

** Client (please complete the following information):**

- OS: Windows
- Browser Firefox
- Version 126.0b8 (64-bit)

**Platform (Please tell us which deployment version you are using)**
Teable.io and Docker both have same issues

**Additional context**
N/A

**Comment by tea-artist** [comment]
This is a known issue and we will fix it #543

**Comment by solankimihir** [comment]
I am dumb! The original issue is also created by me. :smh: .
Closing this issue. My apologies for the duplication.
