### ISSUE TITLE
Unable to import linked records when importing excel/csv

### ISSUE THREAD

**Issue by solankimihir** [teableio/teable#585]
**Describe the bug**
When importing records in an existing table, I am unable to import values in a field if it is linked to another table.

**To Reproduce**
Create a Client table and Tasks table, and link them:
Client table would look like this:
![image](https://github.com/teableio/teable/assets/66866380/f54ffde6-648b-48e6-8a89-f084dfe253f3)

Tasks Table would look like this:
![image](https://github.com/teableio/teable/assets/66866380/88a7625b-77e0-44a4-9b08-cd38fa323b32)

Notice that the Tasks in Tasks Table are linked to a client. Based on that linked client, the "Mapped to" is being lookedup from Client Table.

When I import additional tasks from Excel file into the Tasks table, I am unable to specify "Clients".

Screenshot of input file below:
![image](https://github.com/teableio/teable/assets/66866380/bc12db44-e991-4b5a-848e-090644e08668)

Screenshot of import menu below:
![image](https://github.com/teableio/teable/assets/66866380/1b2442d1-82e0-499d-be91-4bcc7c063328)

**Expected behavior**
As long as I have correct Client names, I should be able to import this.
As a work around I create a "temp_Client Name" column where I import "Client Name" and then I copy paste values form "temp_Client Name" column to "Client Name" column. This copy pasting correctly links the relevant client from Client table in Tasks Table.

**Screenshots**
Screenshots in line above.

** Client (please complete the following information):**

- OS: Windows
- Browser Firefox
- Version 126.0b8 (64-bit)

**Platform (Please tell us which deployment version you are using)**
Teable.io and Docker-Standalone both

**Additional context**
I do copy paste (workaround noted above) from Microsoft Edge, since firefox does not support it yet.

**Comment by caoxing9** [comment]
Appreciate for feed back. It is necessary for in-place import link type field. We'll support it soon.
