### ISSUE TITLE
[Feature Request] Duplicate Rows

### ISSUE THREAD

**Issue by solankimihir** [teableio/teable#587]
**Is your feature request related to a problem? Please describe.**
No its not related to a problem

**Describe the solution you'd like**
I would like an option to duplicate rows. I have a "Tasks" table where I create tasks for my team members. There are few tasks that are repeatative in nature where I just need to change 1 field in the row. 
It would be great if I can just duplicate the existing task(i.e. row) and just update one field in the duplicated row, instead of creating the row from scratch.

**Describe alternatives you've considered**
Currently I add a blank row and copy paste from another row.

**Additional context**
None.

**Comment by tea-artist** [comment]
We'll make it happen when the time is right

**Comment by AliceLanniste** [comment]
@tea-artist hi I am newbie to the project，I have a problem with paste. I read the source code for the paste.
![image](https://github.com/user-attachments/assets/afe34986-0bcf-4e6d-82b6-730313bcaf2d)
It needs clipDataEvent argument ,how to  I get the param.

**Comment by tea-artist** [comment]
@AliceLanniste 
Do you mean to contribute code for this feature?

**Comment by AliceLanniste** [comment]
> @AliceLanniste Do you mean to contribute code for this feature?

ye， I completed copy  via `doCopy` function
![image](https://github.com/user-attachments/assets/3d20dc14-582f-4766-b58a-da2091aefa5d)
I dont' know how to implement paste

**Comment by tea-artist** [comment]
@AliceLanniste  Duplicate a record is different from copying and pasting. It is nothing todo with clipboard and should be done through an API. Select one or several records and achieve copying through the right-click menu. This API should be placed under the selection controller. You can start from there to get familiar with the processing flow of the server side.

**Comment by AliceLanniste** [comment]
> @AliceLanniste Duplicate a record is different from copying and pasting. It is nothing todo with clipboard and should be done through an API. Select one or several records and achieve copying through the right-click menu. This API should be placed under the selection controller. You can start from there to get familiar with the processing flow of the server side.

thank you

**Comment by AliceLanniste** [comment]
@tea-artist  hi ,I complete  duplicate rows. 
![image](https://github.com/user-attachments/assets/82f4c092-a6b4-425f-982f-5495b13481b1)
I am trapped with render. when I  click duplicate menu, it'll show a 'duplicate successful' toast.  
It will only render  if you refresh the web page manually.

**Comment by solankimihir** [comment]
> @tea-artist hi ,I complete duplicate rows. ![image](https://private-user-images.githubusercontent.com/17617116/358833372-82f4c092-a6b4-425f-982f-5495b13481b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwMzgxMTQsIm5iZiI6MTcyNDAzNzgxNCwicGF0aCI6Ii8xNzYxNzExNi8zNTg4MzMzNzItODJmNGMwOTItYTZiNC00MjVmLTk4MmYtNTQ5NWIxMzQ4MWIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDAzMjMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlYjAzMzhjNzI0ODMwMjJhMjBmNDU1ZTBjZTUzY2VjZTRmOGVlNDgzODdmNTI0NGZlYWUyMDY0YTAwMWM3MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P5-dAh9DPBEctKrucTzE8vnEchPeZR90jW9T2aj5VjQ) I am trapped with render. when I click duplicate menu, it'll show a 'duplicate successful' toast. It will only render if you refresh the web page manually.

May be it's because of websocket?
Can you check how the "Add Row" function works? Is there a way it asks websocket to refresh the data stream or something?
