### ISSUE TITLE
License under a more permissive license?

### ISSUE THREAD

**Issue by johnpyp** [teableio/teable#592]
**Is your feature request related to a problem? Please describe.**

For many companies, usage of AGPL software is a non starter, even if there may be ways to technically use/run the software in a compliant way.

Currently, I'm honestly not even sure if I can use the one click hosting offerings in the readme while complying with the AGPL. It could also be completely fine. I have no idea, and because I'm not a lawyer and the AGPL makes this decision way harder than it should be :(

**Describe the solution you'd like**

Assuming the intent is for teable to be used commercially self-hosted, changing the license to be more permissive (or dual licensing), would help a lot.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by tea-artist** [comment]
Thank you for your suggestion. We will consider the problem carefully

**Comment by giddie** [comment]
What's the problem with self-hosting AGPL? Most companies won't be modifying the code, and if they do they'll be able to link to a GitHub fork. Doesn't seem too confusing to me 🤷

**Comment by johnpyp** [comment]
That kind of pattern is GPL 2.0, e.g the Linux Kernel, and works very well.

My understanding is that AGPL takes this much further and makes it, at the least, very risky to effectively run any custom software that interacts with it and which may end up exposed to customers. This is why many tech companies have blanket bans on AGPL software, it's extremely risky.

**Comment by giddie** [comment]
Not particularly - the main addition for AGPL is that if a download link to the source code exists in the software, then it should be retained (and updated) when modifying the code. The idea is to ensure that anyone who uses the software has the ability to inspect, download, and themselves modify the source code that is running the system they are interacting with. It's not particularly difficult to comply with as a business...

**Comment by almereyda** [comment]
I'm suggesting to close here. AGPL is a very sane choice for a web application.

**Comment by tea-artist** [comment]
We've updated the licensing for packages under the 'packages' directory to the more permissive MIT license. This change:

Allows users to retain full rights to plugins and peripheral systems developed for Teable.
Facilitates broader integration and use of these components.
Encourages innovation within our community.
The core applications remain under the AGPL-3.0 license, maintaining our commitment to open-source principles.

#844
