### ISSUE TITLE
Formula column rendering issue

### ISSUE THREAD

**Issue by Demo7783** [teableio/teable#597]
There are issues with the formula's front-end. For instance, I've created a countdown for the number of days, but the front-end page doesn't dynamically update it.
When I created it, there were 5 days remaining, but after 1 day, the days were still displayed as 5. This doesn't change dynamically unless I manually update the list.

Demo：https://app.teable.io/share/shrGcecmw7qNPICoP51/view
The formula rendering on May 10th is as follows
![image](https://github.com/teableio/teable/assets/60234233/76aa5fb9-159a-40ff-8cee-bada22f6a555)

**Comment by tea-artist** [comment]
Functions related to "now" do not refresh automatically yet, It only recalculates when the dependencies change.
Include `NOW` `FROMNOW` `TONOW` `TODAY`.

**Comment by Demo7783** [comment]
Okay, understood. Thank you for your assistance
