### ISSUE TITLE
when export csv if table name contains china charactor ,it will fail

### ISSUE THREAD

**Issue by GitLaser** [teableio/teable#598]
![image](https://github.com/teableio/teable/assets/26178237/a046275a-9fd7-457a-8199-6d4a7cc11b3e)

**Comment by GitLaser** [comment]
![image](https://github.com/teableio/teable/assets/26178237/5609a4f2-82ca-44d6-b8fd-cab1daf75144)

**Comment by caoxing9** [comment]
Well, appreciate for reporting this. I've got the reason is that response's header encoding. I'll fix it as soon as possible. Thanks for feedback～
