### ISSUE TITLE
cannot log in with github account

### ISSUE THREAD

**Issue by Tuscan-blue** [teableio/teable#613]
**Describe the bug**  
Cannot log in with github account. It always shows "No email provided from Github"

**To Reproduce**
1. Go to https://app.teable.io/auth/login
2. Click on 'Github' button
3. Input email and password, then submit

**Expected behavior**
Be able to log in with a github account.

**Screenshots**
![image](https://github.com/teableio/teable/assets/141131070/49ae885e-3a19-4b4b-bedc-5fe398562160)

**Client**
- OS: Windows11
- Browser: Chrome, MicroSoft Edge

**Platform**
teable.io

**Additional context**
None

**Comment by boris-w** [comment]
To log in with your GitHub account, please ensure that you have set a Public email address in your GitHub profile settings.

**Comment by Tuscan-blue** [comment]
Thanks!
