### ISSUE TITLE
[Bug Report] Broken Redirection after Sucessful Change Password

### ISSUE THREAD

**Issue by solankimihir** [teableio/teable#626]
**Describe the bug**
After successfully changing the password from Settings menu, the page is redirected to home page or some other page. This causes the app to show an error.
Screenshot below:
![image](https://github.com/teableio/teable/assets/66866380/325146e4-9133-49dc-8985-cec8df621c89)
 

**To Reproduce**

1. Open Teable
2. Click on your name on the left bottom side
3. Click on settings
4. Click on Change Password (Refer screenshot below)
5. Input current password and new passwords.
6. Click on "Change Password".
7. Wait for it to redirect.
![image](https://github.com/teableio/teable/assets/66866380/a27b4157-11e8-4911-885d-095ba16e20b9)

**Expected behavior**
It should not redirect anywhere.

**Screenshots**
Screenshot inline above.

** Client (please complete the following information):**

- OS: Windows 
- Browser : Firefox 
- Version : 127.0b6 

**Platform (Please tell us which deployment version you are using)**
teable.io, docker-standalone

**Additional context**
N/A

**Comment by boris-w** [comment]
Yes, this is something we missed. I will fix it shortly.
