### ISSUE TITLE
Adding password to share form link causes "404 page not found"

### ISSUE THREAD

**Issue by tylerdurden4285** [teableio/teable#658]
**Describe the bug**
Sharing the form works fine unless I add a password requirements and then it always shows "404 page not found" message. 

**To Reproduce**
Installed on localhost using the same docker compose install instructions on the github main page. Installed and works fine besides this issue. 

**Expected behavior**
Expected to perhaps see a field that accepts a password in order to access the form. 

**Screenshots**
![image](https://github.com/teableio/teable/assets/97774114/9a6a45d1-78b2-443a-aa50-653c11e57aaa)

** Client (please complete the following information):**

- OS: Zorin OS 17.1 Core
- Browser Brave

**Platform (Please tell us which deployment version you are using)**
- Teable Version 1.2.0 docker compose install

**Additional context**
Example of the type of link I am testing: http://localhost:3000/share/shryKAXSUbbB02gBw2w/view

**Comment by tylerdurden4285** [comment]
Does that mean this was fixed? Just wanting to check as I'm still new with issues on github. Thanks

**Comment by boris-w** [comment]
> Does that mean this was fixed? Just wanting to check as I'm still new with issues on github. Thanks

Yes, it's been fixed.
