### ISSUE TITLE
Deleting row from mobile interface

### ISSUE THREAD

**Issue by giddie** [teableio/teable#668]
**Describe the bug**
It appears to be impossible to delete a row from the mobile interface.

**To Reproduce**

* Long-pressing does nothing, anywhere on the row.
* Clicking on the row opens an edit form.
* Neither the form nor the grid view offers a delete button for the row.
* I can't see a way to select rows for some batch delete action either.

**Expected behavior**
* Long-pressing on the row should bring up an actions menu (or select the row)
* The edit form should contain an actions menu.
* When rows are selected, either:
  * Long-pressing them should raise an actions menu, or
  * A bulk actions menu should become available in the tool bar

**Client**

- OS: Android
- Firefox for Android
- 127.0

**Platform (Please tell us which deployment version you are using)**
docker-standalone

**Comment by spiritanand** [comment]
@tea-artist /maintainers I would like to work on this issue, please assign

**Comment by spiritanand** [comment]
@tea-artist which direction do we want to go in? 
- Do we add an actions menu on long-press
- (or much simpler and consistent) just add a delete row button in the edit form that opens up on tap?

**Comment by tea-artist** [comment]
@spiritanand Thank you! the second one is good, add a "more" button to show the delete option in the drop-down

like this
<img width="303" alt="image" src="https://github.com/user-attachments/assets/6d028216-6773-4970-af1a-cea1b7ce1095">
