### ISSUE TITLE
When I choose to download CSV and the content is in Simplified Chinese, the downloaded file is garbled.

### ISSUE THREAD

**Issue by happy0108** [teableio/teable#685]
I suspect it's an encoding issue because the content is normal in the database. Is there a place where I can choose the encoding?

**Comment by caoxing9** [comment]
Appreciate feedback. Well, i just download a table with simplified chinese content, but it doesn't reproduce, could you please provide more particular detail.

**Comment by happy0108** [comment]
I want to know what details I should provide. I deployed it using Docker Compose.

**Comment by caoxing9** [comment]
> I want to know what details I should provide. I deployed it using Docker Compose.

If the data is not private, provide me the table content like csv, or make the random content with  Simplified Chinese which could reproduce.

**Comment by happy0108** [comment]
I have figured out, I need save as UTF-8 BOM. Then it can recorgnized by excel correctly
