### ISSUE TITLE
Internal server error show when create a new table from csv file

### ISSUE THREAD

**Issue by mickey3721** [teableio/teable#690]
**Describe the bug**
when create new table by importing csv file, failure by internal error message

**To Reproduce**

1. Go to user space
2. Click on 'create database'
3. Click on '+'
4. Click on 'from cvs file'
5. choose local file, add upload local csv file
6. See the error message

**Expected behavior**
how to solve the problem? 

**Screenshots**
![image](https://github.com/teableio/teable/assets/60539185/767ba1b8-a84c-4150-ab0e-bcc51f3c8917)

** Client (please complete the following information):**

- OS: [linux mint]
- Browser [edge]
- Version [latest]

**Platform (Please tell us which deployment version you are using)**
[docker-standalone, with expose port change 3000 to 3200]

**Additional context**
I try the web demo with the same file is success to create the table, but failure in docker self-hosting

**Comment by caoxing9** [comment]
It seems that file doesn‘t upload successfully, you can test it by uploading file
In a table using attachment field. What’s more, you also could see the log.

**Comment by mickey3721** [comment]
Log message during the operation:

teable-1             | {"level":30,"time":1720064582190,"pid":1,"hostname":"dca5aaf58e26","name":"teable","req":{"id":"f887fc3b8a7795512ac336b0c73f00cf","method":"GET","url":"/api/import/analyze?attachmentUrl=http:%2F127.0.0.1:3200%2Fapi%2Fattachments%2Fread%2Fprivate%2Ftable%2FwehIsDQB3Rc5%3Ftoken%3Dffb51a5c7c3d9eb4ee3b941550bd3f00dcd999b2a385487795a4820b9131585edda373c719e8719685ccdc233f0291260db10795b2fe5b3683dd907abe92bda67fc50efc0781a58bb3497dbe3798385a&fileType=csv","query":{"attachmentUrl":"http:/127.0.0.1:3200/api/attachments/read/private/table/wehIsDQB3Rc5?token=ffb51a5c7c3d9eb4ee3b941550bd3f00dcd999b2a385487795a4820b9131585edda373c719e8719685ccdc233f0291260db10795b2fe5b3683dd907abe92bda67fc50efc0781a58bb3497dbe3798385a","fileType":"csv"},"params":{"0":"api/import/analyze"},"remoteAddress":"::ffff:192.168.0.137","remotePort":9968},"res":{"statusCode":500},"err":{"type":"Error","message":"failed with status code 500","stack":"Error: failed with status code 500\n    at onResFinished (/app/node_modules/.pnpm/pino-http@9.0.0/node_modules/pino-http/logger.js:114:39)\n    at ServerResponse.onResponseComplete (/app/node_modules/.pnpm/pino-http@9.0.0/node_modules/pino-http/logger.js:177:14)\n    at /app/node_modules/.pnpm/@opentelemetry+context-async-hooks@1.22.0_@opentelemetry+api@1.8.0/node_modules/@opentelemetry/context-async-hooks/build/src/AbstractAsyncHooksContextManager.js:50:55\n    at AsyncLocalStorage.run (node:async_hooks:335:14)\n    at AsyncLocalStorageContextManager.with (/app/node_modules/.pnpm/@opentelemetry+context-async-hooks@1.22.0_@opentelemetry+api@1.8.0/node_modules/@opentelemetry/context-async-hooks/build/src/AsyncLocalStorageContextManager.js:33:40)\n    at ServerResponse.contextWrapper (/app/node_modules/.pnpm/@opentelemetry+context-async-hooks@1.22.0_@opentelemetry+api@1.8.0/node_modules/@opentelemetry/context-async-hooks/build/src/AbstractAsyncHooksContextManager.js:50:32)\n    at ServerResponse.emit (node:events:526:35)\n    at ServerResponse.emit (node:domain:488:12)\n    at onFinish (node:_http_outgoing:1005:10)\n    at callback (node:internal/streams/writable:608:21)"},"responseTime":345,"spanId":"3f442ea6da7d676c","traceId":"f887fc3b8a7795512ac336b0c73f00cf","msg":"request errored"}

**Comment by caoxing9** [comment]
> Log message during the operation:
> 
> teable-1 | {"level":30,"time":1720064582190,"pid":1,"hostname":"dca5aaf58e26","name":"teable","req":{"id":"f887fc3b8a7795512ac336b0c73f00cf","method":"GET","url":"/api/import/analyze?attachmentUrl=http:%2F127.0.0.1:3200%2Fapi%2Fattachments%2Fread%2Fprivate%2Ftable%2FwehIsDQB3Rc5%3Ftoken%3Dffb51a5c7c3d9eb4ee3b941550bd3f00dcd999b2a385487795a4820b9131585edda373c719e8719685ccdc233f0291260db10795b2fe5b3683dd907abe92bda67fc50efc0781a58bb3497dbe3798385a&fileType=csv","query":{"attachmentUrl":"http:/127.0.0.1:3200/api/attachments/read/private/table/wehIsDQB3Rc5?token=ffb51a5c7c3d9eb4ee3b941550bd3f00dcd999b2a385487795a4820b9131585edda373c719e8719685ccdc233f0291260db10795b2fe5b3683dd907abe92bda67fc50efc0781a58bb3497dbe3798385a","fileType":"csv"},"params":{"0":"api/import/analyze"},"remoteAddress":"::ffff:192.168.0.137","remotePort":9968},"res":{"statusCode":500},"err":{"type":"Error","message":"failed with status code 500","stack":"Error: failed with status code 500\n at onResFinished (/app/node_modules/.pnpm/pino-http@9.0.0/node_modules/pino-http/logger.js:114:39)\n at ServerResponse.onResponseComplete (/app/node_modules/.pnpm/pino-http@9.0.0/node_modules/pino-http/logger.js:177:14)\n at /app/node_modules/.pnpm/@opentelemetry+context-async-hooks@[1.22.0_@opentelemetry](mailto:1.22.0_@opentelemetry)+api@1.8.0/node_modules/@opentelemetry/context-async-hooks/build/src/AbstractAsyncHooksContextManager.js:50:55\n at AsyncLocalStorage.run (node:async_hooks:335:14)\n at AsyncLocalStorageContextManager.with (/app/node_modules/.pnpm/@opentelemetry+context-async-hooks@[1.22.0_@opentelemetry](mailto:1.22.0_@opentelemetry)+api@1.8.0/node_modules/@opentelemetry/context-async-hooks/build/src/AsyncLocalStorageContextManager.js:33:40)\n at ServerResponse.contextWrapper (/app/node_modules/.pnpm/@opentelemetry+context-async-hooks@[1.22.0_@opentelemetry](mailto:1.22.0_@opentelemetry)+api@1.8.0/node_modules/@opentelemetry/context-async-hooks/build/src/AbstractAsyncHooksContextManager.js:50:32)\n at ServerResponse.emit (node:events:526:35)\n at ServerResponse.emit (node:domain:488:12)\n at onFinish (node:_http_outgoing:1005:10)\n at callback (node:internal/streams/writable:608:21)"},"responseTime":345,"spanId":"3f442ea6da7d676c","traceId":"f887fc3b8a7795512ac336b0c73f00cf","msg":"request errored"}

I wanna confirm that whether other simple csv could be imported, and could you send me the file, i'll test in my local. Send me google mail is ok.

**Comment by kevin909** [comment]
```
"attachmentUrl":"http:/127.0.0.1:3200/api/attachments/read/private/table/wehIsDQB3Rc5?token=ffb51a5c7c3d9eb4ee3b941550bd3f00dcd999b2a385487795a4820b9131585edda373c719e8719685ccdc233f0291260db10795b2fe5b3683dd907abe92bda67fc50efc0781a58bb3497dbe3798385a"


**`http:/127.0.0.1:3200`**     少了一个斜杠
```

**Comment by caoxing9** [comment]
#691 are same problem
