### ISSUE TITLE
Unable to import CSV or Excel files

### ISSUE THREAD

**Issue by kevin909** [teableio/teable#691]
![企业微信截图_172015179667](https://github.com/teableio/teable/assets/35388701/15c04745-92ff-40ce-bfb4-7c8ba9d56e57)

1. Uploaded attachments cannot be displayed.
2. Unable to import CSV or Excel files (prompting format error).

(/api/attachments/notify/xxxxxx)
I checked, is there an issue with the interface shown in the screenshot above?

Latest Docker image 1.2.1 ，

**Comment by caoxing9** [comment]
> ![企业微信截图_172015179667](https://private-user-images.githubusercontent.com/35388701/345996224-15c04745-92ff-40ce-bfb4-7c8ba9d56e57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2Njc0NTgsIm5iZiI6MTcyMDY2NzE1OCwicGF0aCI6Ii8zNTM4ODcwMS8zNDU5OTYyMjQtMTVjMDQ3NDUtOTJmZi00MGNlLWJmYjQtN2M4YmE5ZDU2ZTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDAzMDU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzZGUwZDlmY2U4NjA3NjhlNDRmMzM5NjQ1ZmVmMDRlYmM3NDNkMGU5NzViNzE4ZDViYmVhOWJkYWEzMjk2MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n6dgWgGI1aoQ30_KgB4R3U6Nn64NiaNXxY94kpGqx4s)
> 
> 1. Uploaded attachments cannot be displayed.
> 2. Unable to import CSV or Excel files (prompting format error).
> 
> (/api/attachments/notify/xxxxxx) I checked, is there an issue with the interface shown in the screenshot above?
> 
> Latest Docker image 1.2.1 ，

Perhaps you can check the env variable about STORAGE_PREFIX.

**Comment by caoxing9** [comment]
Well, the reason is that when merge url path lost a `/` when you use file mode is local. We'll fix it soon. Thank you for feedback.

**Comment by caoxing9** [comment]
#690 same problem
