### ISSUE TITLE
API Permission Issue: Developer Token with Full Permissions Receives 403 Error on /api/import/analyze Endpoint

### ISSUE THREAD

**Issue by cloudtrekcn** [teableio/teable#700]
Describe the bug
When using a developer token with all permissions granted, the API call to /api/import/analyze returns a 403 Forbidden error. However, the same API call succeeds when logged in as a super user through the Teable API debugging tool.

To Reproduce

Create a developer token with all permissions granted
Make a GET request to /api/import/analyze with the following parameters:
attachmentUrl: https://domain/excel/%E8%81%94%E8%B0%83%E6%95%B0%E6%8D%AE1024.xlsx
fileType: excel
Observe the 403 Forbidden error response
Expected behavior
The API call should succeed and return the expected analysis results for the specified Excel file.

Screenshots
[If you have any screenshots of the error or the API debug tool, please attach them here]

Client (please complete the following information):

OS: [Your OS, e.g., Windows 10, macOS Big Sur]
Browser: [Your browser, e.g., Chrome, Firefox]
Version: [Your browser version, e.g., 91.0.4472.124]
Platform (Please tell us which deployment version you are using)
[Please specify your deployment version, e.g., teable.io, docker-standalone, docker-swarm, docker-cluster]

Additional context
Server log for the failed request:

`{"level":30,"time":1720422607593,"pid":1,"hostname":"teable-7655c5f887-mvp99","name":"teable","req":{"id":"94a18de4116d58d359a01bb833b334f6","method":"GET","url":"/api/import/analyze?attachmentUrl=https%3A%2F%2Fpub-a29bddd96f6c45ca914d6df818c73369.r2.dev%2Fexcel%2F%25E8%2581%2594%25E8%25B0%2583%25E6%2595%25B0%25E6%258D%25AE1024.xlsx&fileType=excel","query":{"attachmentUrl":"https://pub-a29bddd96f6c45ca914d6df818c73369.r2.dev/excel/%E8%81%94%E8%B0%83%E6%95%B0%E6%8D%AE1024.xlsx","fileType":"excel"},"params":{"0":"api/import/analyze"},"remoteAddress":"::ffff:10.60.5.116","remotePort":20542},"res":{"statusCode":403},"responseTime":20,"spanId":"8ae885d8ec7bf353","traceId":"94a18de4116d58d359a01bb833b334f6","msg":"request completed"}
`This issue appears to be related to API permissions. The developer token, despite having all permissions granted, is not being recognized as having the necessary rights to access the /api/import/analyze endpoint. This discrepancy between the developer token permissions and the super user permissions suggests a potential issue with how permissions are being applied or checked for this specific API endpoint.

**Comment by caoxing9** [comment]
> Describe the bug
> 
> When using a developer token with all permissions granted, the API call to /api/import/analyze returns a 403 Forbidden error. However, the same API call succeeds when logged in as a super user through the Teable API debugging tool.
> 
> 
> 
> To Reproduce
> 
> Steps to reproduce the behavior:
> 
> 
> 
> Create a developer token with all permissions granted
> 
> Make a GET request to /api/import/analyze with the following parameters:
> 
> attachmentUrl: https://domain/excel/%E8%81%94%E8%B0%83%E6%95%B0%E6%8D%AE1024.xlsx
> 
> fileType: excel
> 
> Observe the 403 Forbidden error response
> 
> Expected behavior
> 
> The API call should succeed and return the expected analysis results for the specified Excel file.
> 
> 
> 
> Screenshots
> 
> [If you have any screenshots of the error or the API debug tool, please attach them here]
> 
> 
> 
> Client (please complete the following information):
> 
> 
> 
> OS: [Your OS, e.g., Windows 10, macOS Big Sur]
> 
> Browser: [Your browser, e.g., Chrome, Firefox]
> 
> Version: [Your browser version, e.g., 91.0.4472.124]
> 
> Platform (Please tell us which deployment version you are using)
> 
> [Please specify your deployment version, e.g., teable.io, docker-standalone, docker-swarm, docker-cluster]
> 
> 
> 
> Additional context
> 
> Server log for the failed request:
> 
> 
> 
> `{"level":30,"time":1720422607593,"pid":1,"hostname":"teable-7655c5f887-mvp99","name":"teable","req":{"id":"94a18de4116d58d359a01bb833b334f6","method":"GET","url":"/api/import/analyze?attachmentUrl=https%3A%2F%2Fpub-a29bddd96f6c45ca914d6df818c73369.r2.dev%2Fexcel%2F%25E8%2581%2594%25E8%25B0%2583%25E6%2595%25B0%25E6%258D%25AE1024.xlsx&fileType=excel","query":{"attachmentUrl":"https://pub-a29bddd96f6c45ca914d6df818c73369.r2.dev/excel/%E8%81%94%E8%B0%83%E6%95%B0%E6%8D%AE1024.xlsx","fileType":"excel"},"params":{"0":"api/import/analyze"},"remoteAddress":"::ffff:10.60.5.116","remotePort":20542},"res":{"statusCode":403},"responseTime":20,"spanId":"8ae885d8ec7bf353","traceId":"94a18de4116d58d359a01bb833b334f6","msg":"request completed"}
> 
> `This issue appears to be related to API permissions. The developer token, despite having all permissions granted, is not being recognized as having the necessary rights to access the /api/import/analyze endpoint. This discrepancy between the developer token permissions and the super user permissions suggests a potential issue with how permissions are being applied or checked for this specific API endpoint.
> 
> 
Well，I found the reason is that this api doesn’t set to any source. I ‘ll fix it soon. Appreciate for feedback.
