### ISSUE TITLE
Link is not Working

### ISSUE THREAD

**Issue by Krish-farmd** [teableio/teable#755]
**Describe the bug**
There are two tables, when I am linking with one with another with many to one relation, getting the error:

Crash!
This view is broken. If the refresh still fails, run the data repair program.

Is this a bug, or how to do the link correctly? and Also how to run the data repair programme?

**Comment by tea-artist** [comment]
Could you provide the steps to reproduce this issue? We are very concerned about such problems, and if we can replicate it, we will fix it as soon as possible.

**Comment by Krish1015** [comment]
Please find the photos and video
![IMG_1897](https://github.com/user-attachments/assets/e90d5858-fd7e-4df6-8421-4a6646bc73a4)
![IMG_1898](https://github.com/user-attachments/assets/b32e87ba-3c24-4e9f-a243-2939dbaeba13)
![IMG_1899](https://github.com/user-attachments/assets/6098cb1e-a109-4a6d-b5a1-436c4db42cea)
![IMG_1900](https://github.com/user-attachments/assets/de942379-3e53-486a-94fb-d4b4732cc6d1)
![IMG_1901](https://github.com/user-attachments/assets/2d7b9a78-ef62-421a-a764-e0f95362e064)

https://github.com/user-attachments/assets/c6dfc32d-bba8-42ac-9a34-1aa7d4ae17ea
