### ISSUE TITLE
File import, when re-importing a file, the primary key is ignored for updates

### ISSUE THREAD

**Issue by Roman2nc** [teableio/teable#772]
**Describe the bug**
Duplicate rows when primary key is defined
Normally, the application would update the rows 

**To Reproduce**
1 - create table from excel file
2 - import data from menu context on table
![image](https://github.com/user-attachments/assets/36240cfe-c6bf-4587-bacb-594cd7239851)

**Comment by caoxing9** [comment]
I didn't quite understand your meaning, could you be more specific?
