### ISSUE TITLE
  can not drop table ,and error .

### ISSUE THREAD

**Issue by tututu123** [teableio/teable#780]
**Describe the bug**
If you import a  .xlsx file, there are two sheets in the file, one of which is empty. teable will also import the empty sheet into the database, and can not delete  empty sheet .   but  .csv is good .

**To Reproduce**
always loading .
<img width="1271" alt="image" src="https://github.com/user-attachments/assets/5aa6854d-f336-4718-b0d2-c0d4e2dc882a">

**Comment by tututu123** [comment]
if you drop empty table :
<img width="408" alt="image" src="https://github.com/user-attachments/assets/90a63fc1-043a-4b94-925c-68510f161170">

**Comment by ZHWang12138** [comment]
same error
