### ISSUE TITLE
Deploy on Railway does not work

### ISSUE THREAD

**Issue by timothoms** [teableio/teable#789]
**Describe the bug**

"Deploy on Railway" with default settings crashes immediately after deployment. (Using Hobby plan on Railways.app.)

**To Reproduce**

1. Click on "Deploy to Railway"
2. On Railway Template page, without changing any settings or environment variables, click on "Deploy".
3. Deployment crashes.

**Expected behavior**
This should work out of the box (as it did a couple of months ago).

**Screenshots**
<img width="725" alt="Screenshot 2024-08-04 at 6 08 51 PM" src="https://github.com/user-attachments/assets/e63ab17e-1ff6-4426-ace7-7314e03049e1">

**Comment by tea-artist** [comment]
I'll take a look

**Comment by tea-artist** [comment]
The replacement of some environment variables caused some errors in the old template.
It has been fixed. Deploy it from the template again.

**Comment by timothoms** [comment]
Thank you!
