### ISSUE TITLE
Enterprise Feature / Admin API bearer

### ISSUE THREAD

**Issue by Ednn0nd1au** [teableio/teable#821]
- how to purchase Enterprise license?
- do current admin user have access to admin api? seems that 
`{"message":"Forbidden resource","status":403,"code":"restricted_resource"}`
for admin api under admin role user's token

**Comment by tea-artist** [comment]
Hi @Ednn0nd1au 
The enterprise version image is under test and has not been officially launched. You can email support@teable.io and we will send you the test license to experience it.

Admin API is not for token access now, but that's a reasonable need, and we'll get there soon.

**Comment by Ednn0nd1au** [comment]
> support@teable.cn

Thanks @tea-artist , email just sent to that address

**Comment by tea-artist** [comment]
> > [support@teable.cn](mailto:support@teable.cn)
> 
> Thanks @tea-artist , email just sent to that address

Sorry for the wrong email address, support@teable.io (.cn -> .io)

**Comment by Ednn0nd1au** [comment]
> > > [support@teable.cn](mailto:support@teable.cn)
> > 
> > 
> > Thanks @tea-artist , email just sent to that address
> 
> Sorry for the wrong email address, [support@teable.io](mailto:support@teable.io) (.cn -> .io)

resent

**Comment by tea-artist** [comment]
<img width="1094" alt="image" src="https://github.com/user-attachments/assets/7534a359-705f-4c1c-b384-9c6563f381b6">
If you are the admin user for your instance, you will have these two more options, including the API request permissions below admin
