### ISSUE TITLE
Why don’t I have the dashboard functionality after starting locally with Docker?

### ISSUE THREAD

**Issue by riverlaker** [teableio/teable#824]
![image](https://github.com/user-attachments/assets/8b22cbf1-a29c-47a0-9c04-ae8c693e87f2)

**Comment by tea-artist** [comment]
Hi @riverlaker, the Dashboard has not been released yet.

**Comment by riverlaker** [comment]
邮件已收到，谢谢！
                 ——赵淼

**Comment by tea-artist** [comment]
#860

**Comment by riverlaker** [comment]
邮件已收到，谢谢！
                 ——赵淼
