### ISSUE TITLE
How to write the table directly to the MYSQL database?

### ISSUE THREAD

**Issue by phoenixlucky** [teableio/teable#832]
**Is your feature request related to a problem? Please describe.**
All the data written is in the PostgreSQL database. How do I write to the MySQL database?

**Describe the solution you'd like**
I want to see the content I fill in the MySQL data synchronously, can it be achieved? If so, how do I configure it? Are there any specific cases?

**Describe alternatives you've considered**

**Additional context**

**Comment by tea-artist** [comment]
While Teable primarily uses PostgreSQL, you can synchronize data to MySQL using external tools. Here's a brief guide:

Teable creates a PostgreSQL schema for each base, containing all user-created tables.

To sync to MySQL, consider these open-source or popular tools:

Airbyte (open-source)
Debezium (open-source, real-time CDC)
Navicat (widely used client tool with data synchronization features)
Basic setup:

Connect the tool to both PostgreSQL and MySQL databases
Configure data mapping between source and target tables
Set synchronization frequency
Remember, Teable will continue to interact with PostgreSQL as the primary database. The MySQL copy would be for reference or other use cases.

For detailed instructions, refer to the documentation of your chosen tool. If you need further assistance, please ask!

**Comment by phoenixlucky** [comment]
You still need to use third-party data extraction, and you can't connect directly to MySQL, right?OK，I see. Thank you.

**Comment by kpodp0ra** [comment]
Integrating new databases are kept track in GH-556 issue.
