### ISSUE TITLE
Cover image

### ISSUE THREAD

**Issue by almereyda** [teableio/teable#836]
**Is your feature request related to a problem? Please describe.**

It is currently possible to add attachments, which will all be displayed with a small thumbnail when selected for display in Kanban view. Unfortunately the thumbnails are very small and it is not possible to make out details from the images.

**Describe the solution you'd like**

As a resolution, it can be possible to define a single or multiple cover images, which are displayed more prominently.

There is a special field type, which allows to select a single or multiple items from attachment fields in the current record. These images will be displayed as cover images of a card, which esp. influences Kanban view end expanded record view.

**Describe alternatives you've considered**

The attachment field receives an optional property to set a default image.

**Comment by Sky-FE** [comment]
Currently, the Kanban view supports displaying card cover images.

Here's a brief guide:

<img width="290" alt="image" src="https://github.com/user-attachments/assets/f2a4d2ce-a57b-41d8-9434-004b1198947f">

Additionally, the thumbnails inside the cards can be clicked to expand and view.

**Comment by almereyda** [comment]
Beautiful.

The only thing is that it shows some arrows to the left and the right, even when only one image is uploaded.

![grafik](https://github.com/user-attachments/assets/31ef52ed-2c7a-449d-86a1-2129e018646d)

Is this a new issue?
