### ISSUE TITLE
Release docker image with version as the tag

### ISSUE THREAD

**Issue by ZingLix** [teableio/teable#842]
**Is your feature request related to a problem? Please describe.**
I'm glad to see that [v1.3.2](https://github.com/teableio/teable/releases/tag/v1.3.2) has been released, but when I tried to update the image, I found that I couldn't find the v1.3.2 image on ghcr.io or docker hub. I only found something like `sha-xxx` or `1.3.1-alpha-build.493-arm64`. It's hard to identify which is target image I'd like to update.

**Describe the solution you'd like**
Maybe we can add `${{  github.ref_name }}` in docker push action? Checking whether this value is empty might be required.
https://github.com/teableio/teable/blob/f27e398a97031f3bc3cc97c7f606842296e358ec/.github/workflows/docker-push.yml#L125

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by tea-artist** [comment]
The version string is determined by relying on package.json instead of the git tag. We missed the release package, and one has been added. Thanks for the reminder.

You can now use `1.3.2-alpha-build.495-[arch]` as tag
