### ISSUE TITLE
Redis URI is not defined

### ISSUE THREAD

**Issue by mariushosting** [teableio/teable#851]
BACKEND_CACHE_REDIS_URI=redis://default:redispassenv@teable-cache:6379/0

I Always get Redis URI is not defined when launch the container.

**Comment by mariushosting** [comment]
Solved.

**Comment by xrehpicx** [comment]
how

**Comment by 343max** [comment]
It would be very helpful for everyone who finds this to write down how you solved it instead of not giving any help to others who might find this because it doesn't work for them.

**Comment by mariushosting** [comment]
> It would be very helpful for everyone who finds this to write down how you solved it instead of not giving any help to others who might find this because it doesn't work for them.

Check out my docker compose here: https://mariushosting.com/how-to-install-teable-on-your-synology-nas/
