### ISSUE TITLE
Adding Elestio as deployment option

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [teableio/teable#852]
Hey team,
I am Kaiwalya, Developer Advocate at Elestio. Elestio has been providing options of fully deploying and managing Teable application as shown [here](https://elest.io/open-source/teable). I think it would be a great idea if we can add it to official readme/documentation here.
🔔 In addition to this, if you are interested we provide partnership opportunities with tools we support by revenue share upon addition of this method in docs. If you would like to collaborate, just shoot me an email at [kaiwalya@elest.io](mailto:kaiwalya@elest.io) :)

**Comment by tea-artist** [comment]
Is there a way to use it without binding a credit card?

**Comment by kaiwalyakoparkar** [comment]
Hey @tea-artist, Unfortunately, due to safety reasons credit card is essential. We will be happy to provide you with  credits for testing and trying out. Just send an email at [kaiwalya@elest.io](mailto:kaiwalya@elest.io)

**Comment by tea-artist** [comment]
Hi @kaiwalyakoparkar  Thanks for the PR, please keep Elestio deploying the latest version of Teable.

**Comment by kaiwalyakoparkar** [comment]
Hey @tea-artist, Yes, we update the latest version automatically periodically.
