### ISSUE TITLE
Add gallery view

### ISSUE THREAD

**Issue by eastonLua** [teableio/teable#864]
**Is your feature request related to a problem? Please describe.**
I want an gallery view

**Describe the solution you'd like**
I want a data display view with attachments (pictures) as the main column, which can display data similar to personnel cards, materials, etc.

**Describe alternatives you've considered**
The data in each column is displayed in the form of a card. I can set a cover image and choose the data column I want to display. The cards are stacked in the form of a waterfall.

**Additional context**

![1724833327912](https://github.com/user-attachments/assets/a9eb0455-e958-4c54-96d5-b84b9a8cbf07)

**Comment by eastonLua** [comment]
I can develop this feature. Please assign this task to me

**Comment by emengweb** [comment]
please support custem text field(link to image) as gallery image.

**Comment by nileshtrivedi** [comment]
+1

Also, the card for each record in gallery view should be able to show nested records (has_one/belongs_to/has_many/many_to_many relationships). 

This requires a bit of care in implementation as it can trigger the N+1 query problem. See [this discussion in NocoDB repo](https://github.com/nocodb/nocodb/issues/7053).
