### ISSUE TITLE
CSV file import not working

### ISSUE THREAD

**Issue by nicholas-mn** [teableio/teable#877]
**Describe the bug**
A typical CSV file with comma seperators (haven't tested any others) will not be imported.
It gives the error: `File format is not supported, only text/csv,text/tab-separated-values are supported`

**To Reproduce**

1. Go to any base
2. Click on `+ (create new table)`
3. Click `Add from other sources -> Csv file`
4. Choose any legitimate CSV file

**Client**
- OS: Windows 11
- Browser: Firefox
- Version: 1.4.0+build.514

**Platform**
docker-standalone

**Screenshots**

![teablebugarrow](https://github.com/user-attachments/assets/d304bf14-8faa-470b-a23a-c7fbd2f415d8)

![Teablebug (1)](https://github.com/user-attachments/assets/b95af2ab-fe40-4167-8e4a-c93e2cfc00fc)

**Comment by nicholas-mn** [comment]
[people-100000.csv](https://github.com/user-attachments/files/16836215/people-100000.csv)

Here is the exact file I tried to import in the screenshots

**Comment by tea-artist** [comment]
I tried this file on our latest version and it works both on chrome and firefox. I guess it is possible that the upload action fixes minetype.

**Comment by nicholas-mn** [comment]
> I tried this file on our latest version and it works both on chrome and firefox. I guess it is possible that the upload action fixes minetype.

This is what I see in the Developer Inspect in firefox regarding the mimetype when uploading the previous mentioned CSV file

![billede](https://github.com/user-attachments/assets/8104d5e9-f0a6-4f69-a2dd-527f9f6d84a7)

![billede](https://github.com/user-attachments/assets/c26d8933-f84f-4a08-a665-727f0136606f)

**Comment by tea-artist** [comment]
This mineType indicates that it is an xls file, and may need to be re-saved as the following using excel to fix this problem

**Comment by nicholas-mn** [comment]
Well it is just a sample CSV file found on the web - it should not have anything to do with Excel. Very weird.
I think Windows might have something to do with defining the mimetype as an excel file.

I tried importing as Excel and it worked - I bet if i took this file over to a Linux machine and uploaded from there, there wouldn't be any problems with CSV import. Unable to check at the moment though.
