### ISSUE TITLE
Show PDFs directly in the browser

### ISSUE THREAD

**Issue by juliusv** [teableio/teable#913]
In Airtable, I often need to open PDFs from attachment fields and look at them quickly to extract some data from them. Airtable renders the PDF directly overlaid over the interface without having to download any file. It seems like currently in Teable, clicking on a PDF attachment just says "PDF" in big letters and offers you to download the file, but doesn't show you its contents. Would be nice if that was supported!

**Comment by vr-varad** [comment]
@tea-artist I would like to work on this issue if its open for contribution?

**Comment by tea-artist** [comment]
Sure, contributions are welcome! If you need any help, just let us know.

**Comment by nklmantey** [comment]
@tea-artist is this issue still open?

**Comment by tea-artist** [comment]
@nklmantey shipped at #1025
