### ISSUE TITLE
不懂就问，这个求和，求平均数，最小值在哪里调出来？怎么找了半天找不到

### ISSUE THREAD

**Issue by solider245** [teableio/teable#914]
![image](https://github.com/user-attachments/assets/b212cdeb-6e1f-49bd-be3d-448e2c67d2da)

不懂就问，这个求和、求平均数、最小值在哪里调出来？怎么找了半天找不到，帮助里也找了半天了。

麻烦您抽空解决一下。

If you don't understand, ask. Where can I find the sum, average, and minimum values? I've been looking for a long time but can't find them. I've also searched in the help for a long time.

Please take the time to solve this problem.

**Comment by tea-artist** [comment]
Just click on the bottom area of the grid view to select the statistical calculation method.

**Comment by solider245** [comment]
点击之后只会跳出新的输入。并没有你说的选项。方便录一个视频过着gif吗？
After clicking, only a new input appears. There is no option as you
mentioned. Could you record a video or GIF for convenience?

**Comment by tea-artist** [comment]
Maybe it's because you're using a touchscreen device (Phone, iPad or something like that), we have noticed this bug and will fix it soon.
