### ISSUE TITLE
Latest images crashing

### ISSUE THREAD

**Issue by MyWay** [teableio/teable#931]
Latest docker images are crashing with these messages for me:
```
{"level":30,"time":1726821759455,"pid":7,"hostname":"0dee3821f90e","name":"teable","context":"RouterExplorer","msg":"Mapped {/api/comment/:tableId/:recordId/:commentId/reaction, DELETE} route"}
{"level":30,"time":1726821759455,"pid":7,"hostname":"0dee3821f90e","name":"teable","context":"RouterExplorer","msg":"Mapped {/api/comment/:tableId/:recordId/:commentId/reaction, PATCH} route"}
{"level":50,"time":1726821759461,"pid":7,"hostname":"0dee3821f90e","name":"teable","context":"MailerService","msg":"Error occurred while verifying the transporter}: getaddrinfo ENOTFOUND smtp.teable.io"}
- info Sourcemaps generation have been disabled through NEXT_BUILD_ENV_SOURCEMAPS
- info Sentry enabled for this build
{"level":30,"time":1726821760236,"pid":7,"hostname":"0dee3821f90e","name":"teable","context":"OfficialPluginInitService","spanId":"66fb570d7831ff62","traceId":"95034b173fbc7da56c3ec78d18e0ac96","msg":"Creating official plugin: Chart"}
```

I don't see any other useful detail unfortunately.

**Comment by caoxing9** [comment]
what's your version? EE or CE?

**Comment by MyWay** [comment]
CE, latest

**Comment by caoxing9** [comment]
These's logs that you provide is not include any crash error message.
I wanna know whether you started successfully or start it and crash by using some feature.

**Comment by MyWay** [comment]
Yeah, it's crashing after that message as soon as it starts. It was working with the latest branch of some day ago though.

**Comment by caoxing9** [comment]
Is there any useful information available? I pulled the latest CE image and it works well.
However, it's hard to resolve the issue if there is lacking key information

**Comment by MyWay** [comment]
Yeah, only thing I could do is go back to older version until it works again and then we could check the differences.

**Comment by tea-artist** [comment]
Can you share your docker-compose env config to help us identify (remove the password)

**Comment by MyWay** [comment]
1.4.1-alpha-build.540-amd64 is latest version working for me, I tried it today.

This is my docker-compose.yml:
```
services:
  teable:
    image: ghcr.io/teableio/teable:latest
    container_name: teable
    restart: always
    ports:
      - '9999:3000'
    volumes:
      - teable_data:/app/.assets:rw
    environment:
      TZ: "${TIMEZONE}"
      NODE_OPTIONS: "--max-old-space-size=1024"
      PUBLIC_ORIGIN: "${DOMAIN}"
      PRISMA_DATABASE_URL: "${PRISMA_DATABASE_URL}"
      PUBLIC_DATABASE_ADDRESS: "${PRISMA_DATABASE_URL}"
      PUBLIC_DATABASE_PROXY: ""
    depends_on:
      teable_db_migrate:
        condition: service_completed_successfully
    networks:
      - caddy
      - internal

 teable_db:
    image: postgres:15.4
    restart: always
    expose:
      - '5432'
    volumes:
      - teable_db:/var/lib/postgresql/data:rw
    environment:
      TZ: "${TIMEZONE}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    healthcheck:
      test: ['CMD-SHELL', "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - internal

  teable_db_migrate:
    image: ghcr.io/teableio/teable-db-migrate:latest
    environment:
      TZ: "${TIMEZONE}"
      PRISMA_DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@teable_db:5432/${POSTGRES_DB}"
    depends_on:
      teable_db:
        condition: service_healthy
    networks:
      - internal

networks:
  caddy:
    external: true
  internal:

volumes:
  teable_data: {}
  teable_db: {}
```

**Comment by jdalrymple** [comment]
Hitting the same problem as well, using the CE sample from the docs

**Comment by boris-w** [comment]
> 1.4.1-alpha-build.540-amd64 is latest version working for me, I tried it today.
> 
> This is my docker-compose.yml:
> 
> ```
> services:
>   teable:
>     image: ghcr.io/teableio/teable:latest
>     container_name: teable
>     restart: always
>     ports:
>       - '9999:3000'
>     volumes:
>       - teable_data:/app/.assets:rw
>     environment:
>       TZ: "${TIMEZONE}"
>       NODE_OPTIONS: "--max-old-space-size=1024"
>       PUBLIC_ORIGIN: "${DOMAIN}"
>       PRISMA_DATABASE_URL: "${PRISMA_DATABASE_URL}"
>       PUBLIC_DATABASE_ADDRESS: "${PRISMA_DATABASE_URL}"
>       PUBLIC_DATABASE_PROXY: ""
>     depends_on:
>       teable_db_migrate:
>         condition: service_completed_successfully
>     networks:
>       - caddy
>       - internal
> 
>  teable_db:
>     image: postgres:15.4
>     restart: always
>     expose:
>       - '5432'
>     volumes:
>       - teable_db:/var/lib/postgresql/data:rw
>     environment:
>       TZ: "${TIMEZONE}"
>       POSTGRES_DB: "${POSTGRES_DB}"
>       POSTGRES_USER: "${POSTGRES_USER}"
>       POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
>     healthcheck:
>       test: ['CMD-SHELL', "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
>       interval: 10s
>       timeout: 3s
>       retries: 3
>     networks:
>       - internal
> 
>   teable_db_migrate:
>     image: ghcr.io/teableio/teable-db-migrate:latest
>     environment:
>       TZ: "${TIMEZONE}"
>       PRISMA_DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@teable_db:5432/${POSTGRES_DB}"
>     depends_on:
>       teable_db:
>         condition: service_healthy
>     networks:
>       - internal
> 
> networks:
>   caddy:
>     external: true
>   internal:
> 
> volumes:
>   teable_data: {}
>   teable_db: {}
> ```

What does `BACKEND_STORAGE_PROVIDER` configure?

**Comment by MyWay** [comment]
> > 1.4.1-alpha-build.540-amd64 is latest version working for me, I tried it today.
> > This is my docker-compose.yml:
> > ```
> > services:
> >   teable:
> >     image: ghcr.io/teableio/teable:latest
> >     container_name: teable
> >     restart: always
> >     ports:
> >       - '9999:3000'
> >     volumes:
> >       - teable_data:/app/.assets:rw
> >     environment:
> >       TZ: "${TIMEZONE}"
> >       NODE_OPTIONS: "--max-old-space-size=1024"
> >       PUBLIC_ORIGIN: "${DOMAIN}"
> >       PRISMA_DATABASE_URL: "${PRISMA_DATABASE_URL}"
> >       PUBLIC_DATABASE_ADDRESS: "${PRISMA_DATABASE_URL}"
> >       PUBLIC_DATABASE_PROXY: ""
> >     depends_on:
> >       teable_db_migrate:
> >         condition: service_completed_successfully
> >     networks:
> >       - caddy
> >       - internal
> > 
> >  teable_db:
> >     image: postgres:15.4
> >     restart: always
> >     expose:
> >       - '5432'
> >     volumes:
> >       - teable_db:/var/lib/postgresql/data:rw
> >     environment:
> >       TZ: "${TIMEZONE}"
> >       POSTGRES_DB: "${POSTGRES_DB}"
> >       POSTGRES_USER: "${POSTGRES_USER}"
> >       POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
> >     healthcheck:
> >       test: ['CMD-SHELL', "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
> >       interval: 10s
> >       timeout: 3s
> >       retries: 3
> >     networks:
> >       - internal
> > 
> >   teable_db_migrate:
> >     image: ghcr.io/teableio/teable-db-migrate:latest
> >     environment:
> >       TZ: "${TIMEZONE}"
> >       PRISMA_DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@teable_db:5432/${POSTGRES_DB}"
> >     depends_on:
> >       teable_db:
> >         condition: service_healthy
> >     networks:
> >       - internal
> > 
> > networks:
> >   caddy:
> >     external: true
> >   internal:
> > 
> > volumes:
> >   teable_data: {}
> >   teable_db: {}
> > ```
> 
> What does `BACKEND_STORAGE_PROVIDER` configure?

nothing, so 'local'.

**Comment by boris-w** [comment]
@MyWay  I tried removing Caddy from the docker-compose.yaml, and Docker is working well.

**Comment by MyWay** [comment]
Have you tried starting from an old version and updating? Maybe it's something related to db migrations? No idea.

**Comment by tea-artist** [comment]
Did the teable-db-migrate image update and executed successfully?

**Comment by MyWay** [comment]
Yes. Actually I tried deleting both volumes and it's still crashing. So not a db migration issue apparently.

**Comment by boris-w** [comment]
@MyWay  Can you try using the same Docker image and configuration to start a new container instance? Thank you very much

**Comment by tea-artist** [comment]
Can you confirm the current version of teable-db-migrate? I feel like there may be no update.

**Comment by MyWay** [comment]
I just updated now to latest, both teable's image and teable-db-migrate and it's working again. I restored my db backup, restarted and it's still working, so seems it's solved. I'll close the issue, thanks.

```
ghcr.io/teableio/teable                         latest                        9439d0eb9946   About an hour ago   1.43GB
ghcr.io/teableio/teable-db-migrate              latest                        97158656c77e   About an hour ago   612MB
```
