### ISSUE TITLE
Chart plugin expanding produces "Cannot read properties of undefined"

### ISSUE THREAD

**Issue by HoseinGhanbari** [teableio/teable#961]
Hi

Expanding a chart plugin box of type "Raw Table" is producing `Application error: a client-side exception has occurred (see the browser console for more information).` error with the following context.

Any help would be appreciated.

https://github.com/teableio/teable/blob/fbd1456de23e00b8909a9ae611cd5004a34019cc/plugins/src/app/chart/components/chart/chart-config/form/TableForm.tsx#L143

```shell
TypeError: Cannot read properties of undefined (reading 'width')
at children
```

```ts
(tA, {
className: "space-y-2",
children: [(0,
s.jsx)(tv, {
	label: u("form.width"),
	children: (0,
	s.jsx)(an, {
		value: p[e.column].width,
		onValueChange: t => m(e.column, t)
	})
})
```

**Comment by boris-w** [comment]
This issue has been resolved in the latest docker image.

**Comment by HoseinGhanbari** [comment]
Thank you for your quick response.

It would be a great help if you could check your discord dm.

**Comment by boris-w** [comment]
> Thank you for your quick response.
> 
> It would be a great help if you could check your discord dm.

Okay, I've replied to you on discord.

**Comment by HoseinGhanbari** [comment]
that error still happening

```
image: "ghcr.io/teableio/teable:sha-fbd1456de23e00b8909a9ae611cd5004a34019cc"
```

```
image: "ghcr.io/teableio/teable-db-migrate:sha-fbd1456de23e00b8909a9ae611cd5004a34019cc"
```

**Comment by boris-w** [comment]
I'm sorry about that, it does exist and I'll take care of it later on.
